AWSTemplateFormatVersion: 2010-09-09
Description: Nomad Cluster Workers


Parameters:
  ImageId:
    Type: String
  InstanceType:
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  NomadVersion:
    Type: String
  ConsulVersion:
    Type: String
  ConsulLeader:
    Type: String
    Default: 10.10.10.137


Resources:
  NomadWorkerLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          full_install: [install_cfn, install_docker, install_consul_worker, install_nomad_worker, install_fabio, verify_workers]
        install_cfn:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
              mode: '000400'
              owner: root
              group: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.LaunchConfig.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource NomadWorkerLaunchConfiguration --configsets full_install --region ${AWS::Region}
                runas=root
          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files: [/etc/cfn/cfn-hup.conf, /etc/cfn/hooks.d/cfn-auto-reloader.conf]
        install_consul_worker:
          files:
            /root/consul.zip:
              source: !Sub https://releases.hashicorp.com/consul/${ConsulVersion}/consul_${ConsulVersion}_linux_amd64.zip
              mode: '000644'
              owner: root
              group: root
            /root/consul_config.json:
              content: !Sub |
                {
                  "datacenter": "dc1",
                  "data_dir": "/root/consul",
                  "log_level": "INFO",
                  "server": false,
                  "retry_join": [
                    "{{ CONSUL_LEADER }}"
                  ]
                }
              context:
                CONSUL_LEADER: !Ref ConsulLeader
              mode: '000644'
              owner: root
              group: root
            /etc/init.d/consul:
              source: https://raw.githubusercontent.com/nand0p/nomadic/master/scripts/consul_worker.rc
              mode: '000755'
              owner: root
              group: root
          commands:
            01-install-consul:
              command: unzip /root/consul.zip -d /usr/local/bin
          services:
            sysvinit:
              consul:
                enabled: true
                ensureRunning: true
        install_docker:
          packages:
            yum:
              wget: []
              jq: []
              docker: []
          users:
            ec2-user:
              groups:
                - docker
          services:
            sysvinit:
              docker:
                enabled: true
                ensureRunning: true
        install_nomad_worker:
          files:
            /root/nomad.zip:
              source: !Sub https://releases.hashicorp.com/nomad/${NomadVersion}/nomad_${NomadVersion}_linux_amd64.zip
              mode: '000644'
              owner: root
              group: root
            /root/nomad_workers.hcl:
              content: |
                data_dir = "/root/nomad-data"
                server {
                  enabled = false
                }
                client {
                  enabled = true
                }
                consul {
                  address = "localhost:8500"
                }
              mode: '000644'
              owner: root
              group: root
            /root/fabio.hcl:
              source: https://raw.githubusercontent.com/nand0p/nomadic/master/jobs/fabio.hcl
              mode: '000644'
              owner: root
              group: root
            /etc/init.d/nomad:
              source: https://raw.githubusercontent.com/nand0p/nomadic/master/scripts/nomad_worker.rc
              owner: root
              group: root
              mode: '000755'
          commands:
            01-Install-Nomad:
              command: unzip /root/nomad.zip -d /usr/local/bin
          services:
            sysvinit:
              nomad:
                enabled: true
                ensureRunning: true
        install_fabio:
          commands:
            01-run-fabio-containers:
              command: /usr/local/bin/nomad run /root/fabio.hcl
        verify_workers:
          commands:
            ELBHealthCheck:
              command: !Sub
                'until [ "$state" == "\"InService\"" ]; do state=$(aws --region ${AWS::Region} elb describe-instance-health
                 --load-balancer-name ${NomadLoadBalancer}
                 --instances $(curl -s http://169.254.169.254/latest/meta-data/instance-id)
                 --query InstanceStates[0].State); sleep 10; done'
    Properties:
      AssociatePublicIpAddress: True
      EbsOptimized: False
      IamInstanceProfile: !ImportValue NomadWorkerInstanceProfile
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !ImportValue NomadWorkerSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum -y update
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource NomadWorkerLaunchConfiguration --configsets full_install --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource NomadWorkerASG --region ${AWS::Region}


  NomadWorkerASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      Cooldown: 1
      DesiredCapacity: 3
      HealthCheckGracePeriod: 15
      HealthCheckType: ELB
      LaunchConfigurationName: !Ref NomadWorkerLaunchConfiguration
      LoadBalancerNames:
        - !Ref NomadLoadBalancer
      MaxSize: 10
      MinSize: 1
      Tags:
        - PropagateAtLaunch: True
          Key: Name
          Value: nomad-worker
      VPCZoneIdentifier:
        - !ImportValue NomadPublicSubnet
      #TargetGroupARNs:
      #  - String
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: True
    CreationPolicy:
      ResourceSignal:
        Count: 3
        Timeout: PT10M
      AutoScalingCreationPolicy:
        MinSuccessfulInstancesPercent: 100


  NomadLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      LoadBalancerName: NomadFrontend
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '9999'
          Protocol: HTTP
      Scheme: internet-facing
      SecurityGroups:
        - !ImportValue NomadLoadBalancerSecurityGroup
      Subnets:
        - !ImportValue NomadPublicSubnet


# NOTE: V2 LBs require 2 subnets
#  FabioLoadBalancer:
#    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
#    Properties:
#      SecurityGroups:
#        - !Ref TrustedSecurityGroup
#      Scheme: internet-facing
#      Subnets:
#        - !Ref PublicSubnet
#      Type: application
#      IpAddressType: ipv4
#
#
#  FabioTargetGroup:
#    Type: AWS::ElasticLoadBalancingV2::TargetGroup
#    Properties:
#      Port: 9999
#      Protocol: HTTP
#      TargetType: ip
#      VpcId: !Ref VPC
#
#
#  FabioListener:
#    Type: AWS::ElasticLoadBalancingV2::Listener
#    Properties:
#      DefaultActions:
#        - Type: forward
#          TargetGroupArn: !Ref FabioTargetGroup
#      LoadBalancerArn: !Ref FabioLoadBalancer
#      Port: '80'
#      Protocol: HTTP



Outputs:
  NomadLoadBalancer:
    Value: !GetAtt [NomadLoadBalancer, DNSName]
    Description: FQDN of Nomad Frontend
